### ISSUE TITLE
ERROR:   unpackSIF failed: root filesystem extraction failed: extract command failed: : fork/exec /usr/local/bin/singularity: permission denied

### ISSUE THREAD

**Issue by yhchin1976** [singularityware/singularity#6386] opened 2022-02-18 00:35 UTC
### Version of Singularity:

What version of Singularity are you using? Run: singularity 3.7.2

```
$ singularity --version 3.7.2

```

 singularity build --sandbox blast ubuntu_20.04.sif

### Expected behavior
Edit the content of .sif file and save it as a new .sif named blast.sif.

What did you expect to see when you do...?
a new blast.sif should be generated.

### Actual behavior

What actually happend? Why was it incorrect?
root@genome-VirtualBox:~# singularity build --sandbox blast ubuntu_20.04.sif
INFO:    Starting build...
INFO:    Verifying bootstrap image ubuntu_20.04.sif
ERROR:   unpackSIF failed: root filesystem extraction failed: extract command failed: : fork/exec /usr/local/bin/singularity: permission denied
FATAL:   While performing build: packer failed to pack: root filesystem extraction failed: extract command failed: : fork/exec /usr/local/bin/singularity: permission denied

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

### What OS/distro are you running
ubuntu 20.04

```
$ cat /etc/os-release


```

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.
unpack from  .tar.gz and install manually.

**Comment by DrDaveD** [comment] 2022-02-18 14:51
Since the problem is with fork/exec of /usr/local/bin/singularity I suspect a permission problem with access to that binary when running unprivileged.  Even though you're doing the singularity build as root, I'm pretty sure singularity lowers permissions for much of that time.  

In any case, since active development is only happening on apptainer now, we are asking everyone to submit issues at https://github.com/apptainer/apptainer.  If you need more help, please open a new issue there.  Closing this one.

**Closed as completed by DrDaveD** 2022-02-18 14:51 UTC
